Fix testcode
takumel/rspec_app_exam pull request #1
Opened 2021-03-25 19:00 UTC by takumel

spec/system/task_spec.rbのテストコード修正及びリファクタリングを行いました。
- FIXMEはテストが成功するように修正しました
- TODOはlet及びlet!に書き換えリファクタリングをしました

実装側のコードはいじっていません

下記の画像はテスト結果です
[![Image from Gyazo](https://i.gyazo.com/656f41950804a93f0d59be1758d3bbfa.png)](https://gyazo.com/656f41950804a93f0d59be1758d3bbfa)

2021-03-26 04:44 UTC, yuji91 requested changes
細かい点を指摘しました！

2021-03-26 04:44 UTC, yuji91 commented on spec/system/task_spec.rb
> +        task = create(:task, :done)
あらかじめテストデータを用意したい場合は`let!`を使って記載してみましょう。

2021-03-26 04:44 UTC, yuji91 commented on spec/system/task_spec.rb
> +      let(:task) {create(:task)}
これより１つ上の階層で定義しておけば、各テストケースで定義しなくても済みますね！

2021-03-26 05:36 UTC, takumel commented on spec/system/task_spec.rb
> +        task = create(:task, :done)
あらかじめtaskを生成する必要はなさそうだったのでletを適用しました。

2021-03-26 05:39 UTC, takumel commented on spec/system/task_spec.rb
> +      let(:task) {create(:task)}
最上部にてまとめてみました。
テストは走るのですが疑問が出ました。
taskの削除のテストの際にlet!で上書きしているのですがこれはありな書き方なのでしょうか。
5fe52ec

2021-03-26 06:58 UTC, yuji91 commented on spec/system/task_spec.rb
> +      let(:task) {create(:task)}
> let!で上書きしている

これは上書きして問題ないです！
- `let`で定義して都度必要なタイミングでFactoryを作成させる
- `let!`であらかじめ作成したいテストデータを個別のテストケースに記載する

というような形になりますね！

2021-03-26 07:03 UTC, yuji91 requested changes
細かい点を指摘しました！

2021-03-26 07:03 UTC, yuji91 commented on spec/system/task_spec.rb
> +    context '正常系' do
スペース入っているのでご確認ください。

全体のファイル差分に問題がないかを確認すると良いでしょう。
https://github.com/takumel/rspec_app_exam/pull/1/files

2021-03-26 07:03 UTC, yuji91 commented on spec/system/task_spec.rb
> +
不要な改行が残っていますね。

2021-03-26 07:03 UTC, yuji91 commented on spec/system/task_spec.rb
> +      fit 'Taskが削除されること' do
`fit`が設定されているので、このテストケースしか実行されないようになっています。

2021-03-26 07:03 UTC, yuji91 commented on spec/system/task_spec.rb
> +
余計な改行がありますね。

2021-03-26 07:04 UTC, yuji91 commented on spec/system/task_spec.rb
> +        task = create(:task, :done)
`既にステータスが完了のタスク`を変更するという条件は満たせていますか？

2021-03-26 07:04 UTC, yuji91 requested changes
こちらも回答したので、ご確認お願いします。
https://github.com/takumel/rspec_app_exam/pull/1#discussion_r602055637

2021-03-26 09:13 UTC, takumel commented on spec/system/task_spec.rb
> +      let(:task) {create(:task)}
わかりました。ありがとうございます！

2021-03-26 10:09 UTC, takumel commented on spec/system/task_spec.rb
> +        task = create(:task, :done)
ヒントの意味はわかりました！使うのであればlet!だと思います。

そして質問なのですが、ここのit内でのみtraitを利用したtaskの作成をしたいのですが`task = create(:task, :done)`をlet!を利用して書く必要はあるのでしょうか？
it内ではletを利用できないし、同じdescribe'Task編集'の他のテストではstatusがdoneになっているtaskを作成するとテストが通らなくなってしまうと思うのですが…

2021-03-26 10:12 UTC, takumel commented on spec/system/task_spec.rb
> +
修正しました！
82b4b91

2021-03-26 10:12 UTC, takumel commented on spec/system/task_spec.rb
> +
修正しました！
82b4b91

2021-03-26 10:12 UTC, takumel commented on spec/system/task_spec.rb
> +    context '正常系' do
修正しました！
82b4b91

2021-03-26 10:15 UTC, takumel commented on spec/system/task_spec.rb
> +      fit 'Taskが削除されること' do
修正しました！
34a011a

2021-03-29 09:55 UTC, yuji91 requested changes
こちらコメントしました！

2021-03-29 09:55 UTC, yuji91 commented on spec/system/task_spec.rb
> +        task = create(:task, :done)
確かにここは`let!`を使うべきケースではなかったですね！
`edit_project_task_path(project, task)`でtaskのFactoryを実行していると思うので、ここで実行するFactoryを「ステータスが完了となっている」テストデータに変更すれば良いかと思います。

2021-03-29 11:00 UTC, yuji91 requested changes
追加でコメントしました！

2021-03-29 11:00 UTC, yuji91 commented on spec/system/task_spec.rb
> +        task = create(:task, :done)
`visit edit_project_task_path(project, task)`で指定している`task`をステータスが`done`であるFactoryを呼び出すように記載を変えてください。

そうすれば`task = create(:task, :done)`と1行事前に実行しているコードが必要なくなると思います。

2021-04-01 06:40 UTC, takumel commented
> 追加でコメントしました！

2021-04-01 07:17 UTC, takumel commented on spec/system/task_spec.rb
> +        task = create(:task, :done)
再三の丁寧な説明ありがとうございました！
おかげで答えにたどり着けました。
`visit edit_project_task_path(project, task)`内の`task`にもtraitないで記述したシンボルを引数に渡すことができるのですね！勉強になりました。
コードを減らすことができました。

2021-04-01 08:53 UTC, yuji91 approved these changes
修正確認しました。LGTMです。

一度closeされていて前の指摘事項に対してやりとりが出来なくなっているので、その点だけ今後お気をつけ下さい。

2021-04-04 16:31 UTC, merged